force-app/main/default/objects/G4G_Gics__c/G4G_Gics__c.object-meta.xml
<CustomObject>
    <label>Gic</label>
    <nameField>
        <label>Gics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/G4G_Gics__c/fields/G4G_Active__c.field-meta.xml
<CustomField>
    <fullName>G4G_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/G4G_Gics__c/fields/G4G_IndustryFX__c.field-meta.xml
<CustomField>
    <fullName>G4G_IndustryFX__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industry</label>
    <referenceTo>G4G_Gics__c</referenceTo>
    <relationshipLabel>Gics</relationshipLabel>
    <relationshipName>Gics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/G4G_Gics__c/fields/G4G_Parent__c.field-meta.xml
<CustomField>
    <fullName>G4G_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>G4G_Gics__c</referenceTo>
    <relationshipLabel>Gics (Parent)</relationshipLabel>
    <relationshipName>Gics1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/G4G_Gics__c/recordTypes/G4G_Industry.recordType-meta.xml
<RecordType>
    <fullName>G4G_Industry</fullName>
    <active>true</active>
    <label>Industry</label>
</RecordType>

force-app/main/default/objects/G4G_Gics__c/recordTypes/G4G_SubIndustry.recordType-meta.xml
<RecordType>
    <fullName>G4G_SubIndustry</fullName>
    <active>true</active>
    <label>Sub-Industry</label>
</RecordType>

force-app/main/default/classes/G4G_GicsAccountComponent.cls
public with sharing class G4G_GicsAccountComponent {
    @AuraEnabled
    public static List<G4G_Gics__c> getIndustries(){
        return [SELECT Id, Name, G4G_IndustryFX__c FROM G4G_Gics__c WHERE RecordType.DeveloperName = 'G4G_Industry' AND G4G_Active__c = true ORDER BY Name];
    }

    @AuraEnabled
    public static List<G4G_Gics__c> getSubIndustries(String industryId){
        return [SELECT Id, Name, G4G_Parent__c FROM G4G_Gics__c WHERE RecordType.DeveloperName = 'G4G_SubIndustry' AND G4G_Parent__c = :industryId AND G4G_Active__c = true ORDER BY Name];
    }
}